# Generated by Django 2.1.7 on 2019-03-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0004_auto_20190325_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollection',
            name='content_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
